// Code generated by Kitex v0.8.0. DO NOT EDIT.

package hello

import (
	"context"
	hellodemo "github.com/Printemps417/optionloader/examples/hello/kitex_gen/hellodemo"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return helloServiceInfo
}

var helloServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Hello"
	handlerType := (*hellodemo.Hello)(nil)
	methods := map[string]kitex.MethodInfo{
		"echo": kitex.NewMethodInfo(echoHandler, newHelloEchoArgs, newHelloEchoResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "hellodemo",
		"ServiceFilePath": `idl/hello.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.8.0",
		Extra:           extra,
	}
	return svcInfo
}

func echoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*hellodemo.HelloEchoArgs)
	realResult := result.(*hellodemo.HelloEchoResult)
	success, err := handler.(hellodemo.Hello).Echo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHelloEchoArgs() interface{} {
	return hellodemo.NewHelloEchoArgs()
}

func newHelloEchoResult() interface{} {
	return hellodemo.NewHelloEchoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Echo(ctx context.Context, req *hellodemo.Request) (r *hellodemo.Response, err error) {
	var _args hellodemo.HelloEchoArgs
	_args.Req = req
	var _result hellodemo.HelloEchoResult
	if err = p.c.Call(ctx, "echo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
